### PR TITLE
fix finding a free port

### PR DESCRIPTION
**Pull request by timstoddard**
addresses finding free port issue mentioned in https://github.com/SoCreate/angular-playground/issues/169

### CODE REVIEW

**Comment by ddehghan** [comment]
Hi Guys - I would suggest testing your solution inside a docker container as well. Docker does some tricky things with IP-tables. The scenario would be CI builds that run inside of docker containers.  

Thanks again for this tool :-)

**Comment by timstoddard** [comment]
@ddehghan Thanks for the suggestion. We have not tested in docker, but we expect that Playground should work fine in a container. If you run into issues using Playground in a container, we welcome you to submit a PR or open an issue.

**Comment by ddehghan** [comment]
Sure. I will test that to see if ti works.

**Comment by ddehghan** [comment]
OK . I tested it inside of docker and it works. You can run multiple dockers each doing check error and at the same time on the host machine run check-error. It all works. 👍

**Pull request merged**
