### PR TITLE
Update to Angular version 9

### PR DESCRIPTION
**Pull request by arroyocode**
Updates angular-playground package to 6.2.0, use Angular version 9 in both package and example-cli project.

### CODE REVIEW

**Comment by oschlegel** [comment]
Could we speed things a little bit up here? I could really need these changes

**Comment by JustinCouto** [comment]
We are nearly done with the upgrade.  We are working on testing it and should have it ready in the next couple of days.  There is a work-around you can use by telling playground to use the non-ivy compiler.  People have posted it here already.  This upgrade to Ivy is nontrivial.  We have had to make a lot of changes to Playground to get it to work with the IVY compiler.  We hope to have more for you soon

**Comment by MitkoTschimev** [comment]
@JustinCouto Sounds amazing! Can't wait for it! great job guys!

**Comment by lurock** [comment]
Moved work to #243

**Pull request closed without merging**
