### PR TITLE
thrown errors in the cli  print to stderr. Beforehand, thrown errr…

### PR DESCRIPTION
**Pull request by pharaxe**
An attempt to fix or at least point towards why #93 is happening for me

### CODE REVIEW

**Comment by pharaxe** [comment]
I moved the catch to configure.ts. I also got rid of the process.exit() call because it didn't play nicely with the [test case](https://github.com/SoCreate/angular-playground/blob/master/packages/angular-playground/cli/test/configure.spec.ts). I think the process object includes the entire test suite, so in that case exiting after the error breaks things.

**Comment by pharaxe** [comment]
I also checked for other thrown errors that were being eaten, and found one. I made a new issue and pull request for it #95 and #96

**Comment by mgmarlow** [comment]
Yes, `process.exit()` will affect the test case, but we can get around it by mocking the exit call. You can modify the `configure.spec.ts` test with this:

```
it('should throw error when failing to load a configuration file', () => {
    const exitSpy = spyOn(process, 'exit');
    const programMock = { config: './no-config.json' };

    expect(() => {
      const config = applyConfigurationFile(programMock);
    }).toThrow();
    expect(exitSpy).toHaveBeenCalledWith(1);
});
```

where `spyOn(process, 'exist');` prevents the actual `process.exit` call. We want to exit the process at those two moments because we want to halt all possibility of the CLI running in those instances. We can call `process.exit(1)`, instead of `err.code` since we already are providing an error message.

Additionally, using `console.error(err.message)` Will append the `"\n"` character automatically, so that is preferred in this case.

**Comment by pharaxe** [comment]
Thanks for letting me make the changes! It's been a good learning experience.

**Comment by mgmarlow** [comment]
No problem, thanks for contributing

**Pull request merged**
